### ISSUE TITLE
Deprecated selector in `gl-md-syntax/index.less`

### ISSUE THREAD

**Issue by scotartt** [uduki-oh-yeah/atom-gl-md-syntax#4]
In `gl-md-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region`

* `.markup.bold,
.markup.strong.emphasis` => `.syntax--markup.syntax--bold,
.syntax--markup.syntax--strong.syntax--emphasis`

* `.markup.heading` => `.syntax--markup.syntax--heading`

* `.markup.italic,
.markup.emphasis:not(.strong)` => `.syntax--markup.syntax--italic,
.syntax--markup.syntax--emphasis:not(.strong)`

* `.markup.underline` => `.syntax--markup.syntax--underline`

* `.markup.strike` => `.syntax--markup.syntax--strike`

* `.markup.heading,
.markup.substitution,
.markup.changed` => `.syntax--markup.syntax--heading,
.syntax--markup.syntax--substitution,
.syntax--markup.syntax--changed`

* `.markup.inserted,
.markup.addition,
.markup.quote` => `.syntax--markup.syntax--inserted,
.syntax--markup.syntax--addition,
.syntax--markup.syntax--quote`

* `.markup.deletion,
.markup.hr` => `.syntax--markup.syntax--deletion,
.syntax--markup.syntax--hr`

* `.markup.link` => `.syntax--markup.syntax--link`

* `.markup.list > .punctuation` => `.syntax--markup.syntax--list > .syntax--punctuation`

* `.markup.raw,
.markup.code` => `.syntax--markup.syntax--raw,
.syntax--markup.syntax--code`

* `.markup .punctuation` => `.syntax--markup .syntax--punctuation`

* `.text.md .md.hr` => `.syntax--text.syntax--md .syntax--md.syntax--hr`

* `.text.md .md.quote` => `.syntax--text.syntax--md .syntax--md.syntax--quote`

* `.text.md .md.list > .punctuation.checkbox` => `.syntax--text.syntax--md .syntax--md.syntax--list > .syntax--punctuation.checkbox`

* `.text.md .md.list.task.completed` => `.syntax--text.syntax--md .syntax--md.syntax--list.syntax--task.syntax--completed`

* `.text.md .md.code.raw` => `.syntax--text.syntax--md .syntax--md.syntax--code.syntax--raw`

* `.text.md .md.emphasis:not(.strong) .strong` => `.syntax--text.syntax--md .syntax--md.syntax--emphasis:not(.strong) .syntax--strong`

* `.text.md .md.table > .punctuation` => `.syntax--text.syntax--md .syntax--md.syntax--table > .syntax--punctuation`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by uduki-oh-yeah** [comment]
ご指摘ありがとうございました。
指摘をいただいたことにも気づかず数年も放置してしまいました。申し訳ありません。

Atomの開発は終了したようですので、こちらのリポジトリもこのまま更新せずに終了したいと思います。
